version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: qwedsaqwe
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    restart: always
#    security_opt:
#      - seccomp:unconfined
#    volumes:
#      - ./mysql:/var/lib/mysql
  web:
    build: .
    environment:
      DB_HOST: db
      DB_USER: testuser
      DB_PASS: test
      DB_NAME: mysql_db
      DB_TABLE_NAME: device_moving_view
      site: localhost
      admin_pass: password
    depends_on:
      - db
    command: sh -c "sleep 15s && node app.js"

    ports:
      - '80:3000'
    restart: on-failure
